'use node';
import { v, ConvexError } from 'convex/values';
import { action, internalQuery, mutation, query } from './_generated/server';
import { internal } from './_generated/api';
import { assertMasterAdminSession } from './utils';
import { S3Client, PutObjectCommand, GetObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';

const category = v.union(v.literal('anak'), v.literal('taruna'), v.literal('dewasa'));
const status = v.union(v.literal('baru'), v.literal('valid'), v.literal('revisi'), v.literal('sudah_input_pbsi'), v.literal('ditolak'));
const docType = v.union(v.literal('foto_profil'), v.literal('dokumen_identitas'));
const MAX_FILE_SIZE = 2 * 1024 * 1024;
const allowed: Record<string, string[]> = { 'image/jpeg': ['jpg', 'jpeg'], 'image/png': ['png'], 'image/webp': ['webp'], 'application/pdf': ['pdf'] };
const clean = (value: string) => value.trim().replace(/\s+/g, ' ');
function ageCategory(dob: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(dob)) throw new ConvexError('Tanggal lahir tidak valid.'); const born = new Date(`${dob}T00:00:00Z`), now = new Date(); if (Number.isNaN(+born) || born.toISOString().slice(0, 10) !== dob || born > now) throw new ConvexError('Tanggal lahir tidak valid atau masa depan.'); let age = now.getUTCFullYear() - born.getUTCFullYear(); if (now.getUTCMonth() < born.getUTCMonth() || (now.getUTCMonth() === born.getUTCMonth() && now.getUTCDate() < born.getUTCDate())) age--; return age < 15 ? 'anak' : age < 18 ? 'taruna' : 'dewasa'; }
function wa(value: string) { const raw = value.replace(/[\s().-]/g, ''); const result = raw.startsWith('08') ? `628${raw.slice(2)}` : raw.startsWith('+62') ? `62${raw.slice(3)}` : raw; if (!/^628\d{7,12}$/.test(result)) throw new ConvexError('Nomor WhatsApp Indonesia tidak valid.'); return result; }
function fileMeta(filename: string, contentType: string, size: number) { const ext = filename.toLowerCase().split('.').pop(); if (!allowed[contentType]?.includes(ext || '') || size <= 0 || size > MAX_FILE_SIZE) throw new ConvexError('File harus JPG, PNG, WEBP, atau PDF maksimal 2 MiB.'); }
function client() { const { R2_ACCOUNT_ID: accountId, R2_ACCESS_KEY_ID: accessKeyId, R2_SECRET_ACCESS_KEY: secretAccessKey, R2_BUCKET_NAME: bucket } = process.env; if (!accountId || !accessKeyId || !secretAccessKey || !bucket) throw new ConvexError('R2 belum dikonfigurasi.'); return new S3Client({ region: 'auto', endpoint: `https://${accountId}.r2.cloudflarestorage.com`, credentials: { accessKeyId, secretAccessKey } }); }

export const create = mutation({ args: { fullName: v.string(), dob: v.string(), gender: v.union(v.literal('putra'), v.literal('putri')), club: v.string(), kabupaten: v.string(), whatsapp: v.string(), email: v.optional(v.string()) }, handler: async (ctx, args) => { const fullName = clean(args.fullName), club = clean(args.club), kabupaten = clean(args.kabupaten), email = args.email ? args.email.trim().toLowerCase() : undefined; if (!fullName || !club || !kabupaten || (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))) throw new ConvexError('Data pendaftaran tidak valid.'); const now = Date.now(), computed = ageCategory(args.dob); const id = await ctx.db.insert('pb_registrations', { ...args, fullName, club, kabupaten, whatsapp: wa(args.whatsapp), email, category: computed, status: 'baru', createdAt: now, updatedAt: now }); await ctx.db.insert('pb_registration_history', { registrationId: id, status: 'baru', createdAt: now }); return { id, category: computed }; } });
export const recordFile = mutation({ args: { registrationId: v.id('pb_registrations'), docType, filename: v.string(), contentType: v.string(), size: v.number() }, handler: async (ctx, args) => { fileMeta(args.filename, args.contentType, args.size); const registration = await ctx.db.get(args.registrationId); if (!registration) throw new ConvexError('Pendaftaran tidak ditemukan.'); const old = await ctx.db.query('pb_registration_files').withIndex('by_registration', q => q.eq('registrationId', args.registrationId)).collect(); for (const item of old.filter(item => item.docType === args.docType)) await ctx.db.delete(item._id); return ctx.db.insert('pb_registration_files', { ...args, category: registration.category, objectKey: `pb/${args.registrationId}/${registration.category}/${args.docType}`, filename: clean(args.filename), createdAt: Date.now() }); } });
export const listAdmin = query({ args: { adminSessionToken: v.string() }, handler: async (ctx, args) => { await assertMasterAdminSession(ctx, args.adminSessionToken); const all = await ctx.db.query('pb_registrations').order('desc').collect(); return Promise.all(all.map(async registration => ({ ...registration, files: await ctx.db.query('pb_registration_files').withIndex('by_registration', q => q.eq('registrationId', registration._id)).collect(), history: await ctx.db.query('pb_registration_history').withIndex('by_registration', q => q.eq('registrationId', registration._id)).collect() }))); } });
export const updateStatus = mutation({ args: { registrationId: v.id('pb_registrations'), status, note: v.optional(v.string()), adminSessionToken: v.string() }, handler: async (ctx, args) => { await assertMasterAdminSession(ctx, args.adminSessionToken); const note = args.note ? clean(args.note) : undefined; await ctx.db.patch(args.registrationId, { status: args.status, reviewNote: note, updatedAt: Date.now() }); await ctx.db.insert('pb_registration_history', { registrationId: args.registrationId, status: args.status, note, createdAt: Date.now() }); } });
export const getRegistration = internalQuery({ args: { registrationId: v.id('pb_registrations') }, handler: (ctx, args) => ctx.db.get(args.registrationId) });
export const getFile = internalQuery({ args: { registrationId: v.id('pb_registrations'), docType }, handler: async (ctx, args) => (await ctx.db.query('pb_registration_files').withIndex('by_registration', q => q.eq('registrationId', args.registrationId)).collect()).find(file => file.docType === args.docType) || null });
export const authorizeMaster = internalQuery({ args: { adminSessionToken: v.string() }, handler: async (ctx, args) => { await assertMasterAdminSession(ctx, args.adminSessionToken); return true; } });
export const uploadUrl = action({ args: { registrationId: v.id('pb_registrations'), docType, filename: v.string(), contentType: v.string(), size: v.number() }, handler: async (ctx, args) => { fileMeta(args.filename, args.contentType, args.size); const registration = await ctx.runQuery(internal.pbRegistration.getRegistration, { registrationId: args.registrationId }); if (!registration) throw new ConvexError('Pendaftaran tidak ditemukan.'); const Key = `pb/${args.registrationId}/${registration.category}/${args.docType}`; return { url: await getSignedUrl(client(), new PutObjectCommand({ Bucket: process.env.R2_BUCKET_NAME, Key, ContentType: args.contentType, ContentLength: args.size }), { expiresIn: 300 }), objectKey: Key }; } });
export const downloadUrl = action({ args: { registrationId: v.id('pb_registrations'), docType, adminSessionToken: v.string() }, handler: async (ctx, args) => { await ctx.runQuery(internal.pbRegistration.authorizeMaster, { adminSessionToken: args.adminSessionToken }); const file = await ctx.runQuery(internal.pbRegistration.getFile, args); if (!file) throw new ConvexError('Dokumen tidak ditemukan.'); return getSignedUrl(client(), new GetObjectCommand({ Bucket: process.env.R2_BUCKET_NAME, Key: file.objectKey, ResponseContentDisposition: `attachment; filename="${file.filename.replace(/[^\w.-]/g, '_')}"` }), { expiresIn: 300 }); } });
